### ISSUE TITLE
Decide: should we expect submitted code to read input from a file, command line, or both?

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#1]
We want to make it easy for Project Lovelace users to submit their code. A few things to consider here:
* Since we want to support many languages, we need to think about which is easier: files or command line arguments.
* We could possibly provide users the option between the two, and add functionality for both in the engine.
* To avoid deterring new users, we could provide boiler-plate code for reading input.

**Comment by ali-ramadhan** [comment]
I would argue for supplying input through stdin and expecting the user to print output to stdout. I think this should work for the vast majority of problems. Some might have tons of data to crunch but I don't think those will show up in the first ~20 problems.

To be honest, I'm also saying this because the two big submission systems I know of (Sphere Online Judge and CodinGame) both use stdin/stdout and they support many languages, so maybe they had good reasons to go with that. CodinGame also has good boilerplate code for each language and each problem.

**Comment by basimr** [comment]
I was also leaning towards using stdin and stdout for its simplicity. Of course, when we want the user's program to solve multiple problems (i.e, multiple inputs sets) we can just call their program once for each input. And now it's even better to hear that it's being used successfully by existing websites.

Even if we supply boilerplate code for parsing files, I'm guessing it's the more tedious option in many programming languages (think C).
