### ISSUE TITLE
Add support for C and C++

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-engine#20]
Plenty of the early feedback from our users included a call to add support for C and C++. This shouldn't be too difficult to do.

**Comment by ali-ramadhan** [comment]
I think the best approach would be to use the `ctypes` module: https://docs.python.org/3/library/ctypes.html

## Example 1: Squaring an integer
```C
// square.c
// Compile with: cc -fPIC -shared -o libsquare.so square.c
int square(int n) {
	return n*n;
}
```
```python
>>> from ctypes import cdll
>>> lib = cdll.LoadLibrary("/home/ada/tmp/pyc/libsquare.so")
>>> lib.square(4)
16
```

## Example 2: reversing a string
```C
// revstr.c
// Compile with: cc -fPIC -shared -o librevstr.so revstr.c
#include <string.h>
char* reverse_string(char* s) {
	int len = strlen(s);

	int i, k;
	char tmp;
	for(i = 0, k = len-1; i < (len/2); i++, k--) {
        	tmp = s[k];
        	s[k] = s[i];
        	s[i] = tmp;
	}
	
	return s;
}
```
```python
>>> import ctypes
>>> from ctypes import cdll
>>> lib = cdll.LoadLibrary("/home/ada/tmp/pyc/librevstr.so")
>>> lib.string_reverse.restype = ctypes.c_char_p  # Setting return value type.
>>> lib.string_reverse(b"1234567890")
b'0987654321'
```
---
Some notes:
* You have to juggle data types (bit more work for e.g. 3D arrays) but otherwise it's 100% Python. By default it assumes an `int` is returned.
* Gotta add the directory with the shared libraries to `LD_LIBRARY_PATH`, or just give the full filepath.
* Returning multiple values will be challenging... Either we return an array (types must all be the same), or we return an array of pointers (probably the way to go?), or a struct (too invasive). We could instead have a return type of `void` and pass in pointers to the "return values" which the function modifies (probably the best solution?).

PS: SWIG is an interesting alternative but you have to write C extensions and it could get messy. Seems perfect if we want to call C from many other languages, but we have the opposite problem...

**Comment by ali-ramadhan** [comment]
For C++ the issue of returning multiple values at least has a nice solution, we can return a `std::tuple`. Not sure how to make it play nice with `ctypes` but should be possible...

**Comment by ali-ramadhan** [comment]
Maybe we can support C++ only through `std::tuple` return types. Users who want to stick to C can just submit code that doesn't rely on C++ features and libraries?

**Comment by ali-ramadhan** [comment]
I should make sure we know how to do lists, 2D arrays, and multiple return types.

**Comment by ali-ramadhan** [comment]
I really think we should go ahead and use `ctypes` but trying to wrap my head around how to support C and C++ properly with it so just gonna throw some notes here.

I'll just start with something super simple though (C only) and worry about arrays and multiple return values later (and C++).

**Good stuff:**
* Don't need to change the problem modules or the solutions at all! This is really important. We don't want our problem modules and engine to get exponentially more complicated as we support more languages.
* All the C/C++ stuff will be isolated in the `run_c.py` and `run_cpp.py` files.
* Function signatures look the same in all languages.
* Users will write functions that return outputs instead of mutating inputs. Not sure if this is a huge plus, but it's definitely beginner-friendly.

**Stuff to figure out:**
* `ctypes` provides C compatible data types, not C++ compatible data types.
  * So for 2D arrays, we can't use `Vector<Vector<Int>>` in C++ even though it's what most people would want to use.
  * To get around this we can write some sort of conversion function that converts a user's output from `vector<vector<int>>` to `int**` or just cast it if we can.
  * **Best solution?** Alternatively, we can write C++ code that converts `std::vector`, `std::string` to Python lists and strings, etc.
* We will need to know the data type of all the outputs in advance (+ size of any arrays).
  * We might be able to support variable-length arrays if we return the array size as an output...
  * Might have to run `solve_test_case` before running the user's code so we can figure out the type of all outputs.
* Unclear how to handle multiple return values in C. We have some options:
  * Include extra input argument that are pointers to the 2+ output variables. The user mutates the contents of the pointers. E.g.
```void f(int in1, double *out1, int *out2) { *out1 = 2*in1; *out2 = in1/2; }```
but this means C/C++ function signatures won't match those of other languages, and we'll have to write extra code to handle this.
  * Return a `std::tuple`. This means forcing users to use C++ for problems that return multiple values. And we'll have to convert the tuple to a Python tuple (this is probably doable).
  * Disable C for problems with multiple return values (last resort).
  * **Best solution?**: For C++ just use a `std::tuple` and convert it to a `PyObject` tuple. For C, force them to use `std::tuple` (same as disabling C for those problems).

**Comment by ali-ramadhan** [comment]
Useful for converting from a C array to a numpy array: https://docs.scipy.org/doc/numpy/reference/routines.ctypeslib.html

**Comment by ali-ramadhan** [comment]
> This shouldn't be too difficult to do.

Yeah... :(
