### ISSUE TITLE
As a user, I want my submissions to undergo static Python code analysis.

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-engine#5]
Can we analyze code files for language (use file extension?), character count, lines of code, comment count, etc. There seem to be [a lot of analyzers](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis) out there. Pylint seems like the obvious choice for Python, SonarQube seems pretty beefy. Maybe we should stick to basic stuff for now.

**Comment by basimr** [comment]
From your perspective, what value does this bring to the user?

I imagine it may be helpful to somehow use the results of the code analysis to help the user improve their programs. However, we want to support many programming languages, so we'd need to add logic for each new language we add for normalizing analysis results to a standard format (because different code analyzers will have different outputs).

**Comment by ali-ramadhan** [comment]
You're right. Sounds a little too messy for now. Seems like SonarQube supports 20+ languages though.

If we store user submitted code we can always retroactively analyze their code. Should we close this for now?

**Comment by basimr** [comment]
> If we store user submitted code we can always retroactively analyze their code. Should we close this for now?

We can definitely re-open the issue and add this feature in later.
